/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: aU6fPsMDSmKqgHWpAbdgs
// Component: oqH1E7yoY1w4

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Header from "../../Header"; // plasmic-import: OuJG8ggWPxG0/component
import DynamicPagePageSection from "../../DynamicPagePageSection"; // plasmic-import: w-k8SPtgF7fV/component
import ScriptsAndGeneralTags from "../../ScriptsAndGeneralTags"; // plasmic-import: zZNx54MRT-Br/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: aU6fPsMDSmKqgHWpAbdgs/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: aU6fPsMDSmKqgHWpAbdgs/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: aU6fPsMDSmKqgHWpAbdgs/projectcss
import sty from "./PlasmicBookingOptions.module.css"; // plasmic-import: oqH1E7yoY1w4/css

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export function generateDynamicMetadata($q: any, $ctx: any) {
  return {
    openGraph: {},
    twitter: {
      card: "summary"
    }
  };
}

createPlasmicElementProxy;

export type PlasmicBookingOptions__VariantMembers = {};
export type PlasmicBookingOptions__VariantsArgs = {};
type VariantPropType = keyof PlasmicBookingOptions__VariantsArgs;
export const PlasmicBookingOptions__VariantProps = new Array<VariantPropType>();

export type PlasmicBookingOptions__ArgsType = {};
type ArgPropType = keyof PlasmicBookingOptions__ArgsType;
export const PlasmicBookingOptions__ArgProps = new Array<ArgPropType>();

export type PlasmicBookingOptions__OverridesType = {
  root?: Flex__<"div">;
  header?: Flex__<typeof Header>;
  freeBox?: Flex__<"div">;
  dynamicPagePageSection?: Flex__<typeof DynamicPagePageSection>;
  scriptsAndGeneralTags?: Flex__<typeof ScriptsAndGeneralTags>;
};

export interface DefaultBookingOptionsProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicBookingOptions__RenderFunc(props: {
  variants: PlasmicBookingOptions__VariantsArgs;
  args: PlasmicBookingOptions__ArgsType;
  overrides: PlasmicBookingOptions__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header)}
          />

          <div
            data-plasmic-name={"freeBox"}
            data-plasmic-override={overrides.freeBox}
            className={classNames(projectcss.all, sty.freeBox)}
          >
            <DynamicPagePageSection
              data-plasmic-name={"dynamicPagePageSection"}
              data-plasmic-override={overrides.dynamicPagePageSection}
              className={classNames(
                "__wab_instance",
                sty.dynamicPagePageSection
              )}
              dataSourceUrl={`https://apigw.paziresh24.com/v1/ui-jahannama/booking_selection_page_ui/${$ctx.query.document_id}`}
            />
          </div>
          <ScriptsAndGeneralTags
            data-plasmic-name={"scriptsAndGeneralTags"}
            data-plasmic-override={overrides.scriptsAndGeneralTags}
            className={classNames("__wab_instance", sty.scriptsAndGeneralTags)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "header",
    "freeBox",
    "dynamicPagePageSection",
    "scriptsAndGeneralTags"
  ],
  header: ["header"],
  freeBox: ["freeBox", "dynamicPagePageSection"],
  dynamicPagePageSection: ["dynamicPagePageSection"],
  scriptsAndGeneralTags: ["scriptsAndGeneralTags"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: typeof Header;
  freeBox: "div";
  dynamicPagePageSection: typeof DynamicPagePageSection;
  scriptsAndGeneralTags: typeof ScriptsAndGeneralTags;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicBookingOptions__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicBookingOptions__VariantsArgs;
    args?: PlasmicBookingOptions__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicBookingOptions__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicBookingOptions__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicBookingOptions__ArgProps,
          internalVariantPropNames: PlasmicBookingOptions__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicBookingOptions__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBookingOptions";
  } else {
    func.displayName = `PlasmicBookingOptions.${nodeName}`;
  }
  return func;
}

export const PlasmicBookingOptions = Object.assign(
  // Top-level PlasmicBookingOptions renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    freeBox: makeNodeComponent("freeBox"),
    dynamicPagePageSection: makeNodeComponent("dynamicPagePageSection"),
    scriptsAndGeneralTags: makeNodeComponent("scriptsAndGeneralTags"),

    // Metadata about props expected for PlasmicBookingOptions
    internalVariantProps: PlasmicBookingOptions__VariantProps,
    internalArgProps: PlasmicBookingOptions__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pagePath: "/booking-options",
      searchParams: {},
      params: {}
    })
  }
);

export default PlasmicBookingOptions;
/* prettier-ignore-end */
