/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: aU6fPsMDSmKqgHWpAbdgs

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsoNzAawMQhZv4 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: oNZAawMQhZV4/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsoNzAawMQhZv4
});
