/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: aU6fPsMDSmKqgHWpAbdgs
// Component: RM0X42We8_T_

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { ApiRequest } from "@/fragment/components/api-request"; // plasmic-import: MhkncRKg2Phv/codeComponent
import Button from "../../Button"; // plasmic-import: oVzoHzMf1TLl/component
import { Input } from "@/fragment/components/input"; // plasmic-import: zLPWSKiKTX83/codeComponent
import { Select } from "@/fragment/components/select"; // plasmic-import: Y7OelJAhX1bB/codeComponent

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_fragment_design_system_css from "../fragment_design_system/plasmic.module.css"; // plasmic-import: h9Dbk9ygddw7UVEq1NNhKi/projectcss
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: aU6fPsMDSmKqgHWpAbdgs/projectcss
import sty from "./PlasmicVajegan.module.css"; // plasmic-import: RM0X42We8_T_/css

import Icon14Icon from "./icons/PlasmicIcon__Icon14"; // plasmic-import: yaBBaS6PnbWa/icon
import Icon19Icon from "./icons/PlasmicIcon__Icon19"; // plasmic-import: os_k03ppp0Vl/icon
import Icon18Icon from "./icons/PlasmicIcon__Icon18"; // plasmic-import: HutF-e5f3sLb/icon
import Icon15Icon from "./icons/PlasmicIcon__Icon15"; // plasmic-import: eCYtXCdflNl8/icon
import ChevronRightIcon from "../fragment_icons/icons/PlasmicIcon__ChevronRight"; // plasmic-import: GHdF3hS-oP_3/icon
import ChevronLeftIcon from "../fragment_icons/icons/PlasmicIcon__ChevronLeft"; // plasmic-import: r9Upp9NbiZkf/icon

createPlasmicElementProxy;

export type PlasmicVajegan__VariantMembers = {};
export type PlasmicVajegan__VariantsArgs = {};
type VariantPropType = keyof PlasmicVajegan__VariantsArgs;
export const PlasmicVajegan__VariantProps = new Array<VariantPropType>();

export type PlasmicVajegan__ArgsType = {};
type ArgPropType = keyof PlasmicVajegan__ArgsType;
export const PlasmicVajegan__ArgProps = new Array<ArgPropType>();

export type PlasmicVajegan__OverridesType = {
  root?: Flex__<"div">;
  apiRequest?: Flex__<typeof ApiRequest>;
  h6?: Flex__<"h6">;
  priorityField?: Flex__<"label">;
  insertBox?: Flex__<"div">;
  input?: Flex__<typeof Input>;
  select?: Flex__<typeof Select>;
};

export interface DefaultVajeganProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicVajegan__RenderFunc(props: {
  variants: PlasmicVajegan__VariantsArgs;
  args: PlasmicVajegan__ArgsType;
  overrides: PlasmicVajegan__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const $globalActions = useGlobalActions?.();

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "keywordTags",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => ({})
      },
      {
        path: "input.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ""
      },
      {
        path: "select.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => "3"
      },
      {
        path: "select.open",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "apiRequest.data",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "apiRequest"
      },
      {
        path: "apiRequest.error",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "apiRequest"
      },
      {
        path: "apiRequest.loading",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "apiRequest"
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_fragment_design_system_css.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.root
      )}
    >
      <ApiRequest
        data-plasmic-name={"apiRequest"}
        data-plasmic-override={overrides.apiRequest}
        className={classNames("__wab_instance", sty.apiRequest)}
        errorDisplay={
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__rtK7
            )}
          >
            <React.Fragment>
              {(() => {
                try {
                  return "خطا:" + $state.apiRequest.error.message;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return "Error fetching data";
                  }
                  throw e;
                }
              })()}
            </React.Fragment>
          </div>
        }
        loadingDisplay={
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__vv4Kw
            )}
          >
            {
              "\u062f\u0631 \u062d\u0627\u0644 \u062f\u0631\u06cc\u0627\u0641\u062a \u0627\u0637\u0644\u0627\u0639\u0627\u062a ... "
            }
          </div>
        }
        method={"GET"}
        onError={async (...eventArgs: any) => {
          generateStateOnChangeProp($state, ["apiRequest", "error"]).apply(
            null,
            eventArgs
          );
        }}
        onLoading={async (...eventArgs: any) => {
          generateStateOnChangeProp($state, ["apiRequest", "loading"]).apply(
            null,
            eventArgs
          );
        }}
        onSuccess={async (...eventArgs: any) => {
          generateStateOnChangeProp($state, ["apiRequest", "data"]).apply(
            null,
            eventArgs
          );
        }}
        ref={ref => {
          $refs["apiRequest"] = ref;
        }}
        url={
          "https://apigw.paziresh24.com/v1/n8n-search/webhook/vajegan/keywords"
        }
      >
        <div className={classNames(projectcss.all, sty.freeBox__puCo5)}>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__dhWo6
            )}
          >
            {
              "\u06a9\u0644\u06cc\u062f\u0648\u0627\u0698\u0647\u200c\u0647\u0627\u06cc \u062c\u0633\u062a\u062c\u0648"
            }
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__p4Om
            )}
          >
            <React.Fragment>
              <React.Fragment>{""}</React.Fragment>
              {
                <h6
                  data-plasmic-name={"h6"}
                  data-plasmic-override={overrides.h6}
                  className={classNames(
                    projectcss.all,
                    projectcss.h6,
                    projectcss.__wab_text,
                    sty.h6
                  )}
                >
                  {
                    "\u0628\u0627 \u0627\u0648\u0644\u0648\u06cc\u062a\u200c\u0628\u0646\u062f\u06cc \u06a9\u0644\u06cc\u062f\u0648\u0627\u0698\u0647\u200c\u0647\u0627\u06cc \u0645\u0631\u062a\u0628\u0637\u060c \u0634\u0627\u0646\u0633 \u062f\u06cc\u062f\u0647\u200c\u0634\u062f\u0646 \u062e\u0648\u062f \u0631\u0627 \u0627\u0641\u0632\u0627\u06cc\u0634 \u062f\u0647\u06cc\u062f."
                  }
                </h6>
              }
              <React.Fragment>{""}</React.Fragment>
            </React.Fragment>
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__ewlfc
            )}
          >
            {
              "\u062a\u0648\u062c\u0647:\u00a0\u00a0\n\n\r\n\u0627\u0646\u062a\u062e\u0627\u0628 \u06cc\u06a9 \u06a9\u0644\u06cc\u062f\u0648\u0627\u0698\u0647\u060c \u062a\u0636\u0645\u06cc\u0646\u06cc \u0628\u0631\u0627\u06cc \u0646\u0645\u0627\u06cc\u0634 \u0634\u0645\u0627 \u062f\u0631 \u062c\u0627\u06cc\u06af\u0627\u0647 \u0628\u0627\u0644\u0627\u062a\u0631 \u0646\u062a\u0627\u06cc\u062c \u062c\u0633\u062a\u062c\u0648\u06cc \u0622\u0646 \u0639\u0628\u0627\u0631\u062a \u0646\u06cc\u0633\u062a \u0648\u0644\u06cc \u0628\u0647 \u0646\u0645\u0627\u06cc\u0634 \u0634\u0645\u0627 \u062f\u0631 \u0622\u0646 \u0639\u0628\u0627\u0631\u062a \u06a9\u0645\u06a9 \u0645\u06cc\u200c\u06a9\u0646\u062f.\u00a0\u00a0\n\n\u0639\u062f\u062f \u0627\u0648\u0644\u0648\u06cc\u062a \u06a9\u0645\u062a\u0631 \u0628\u0647 \u0645\u0639\u0646\u06cc \u0645\u0647\u0645\u062a\u0631 \u0628\u0648\u062f\u0646 \u0622\u0646 \u0627\u0632 \u0646\u0638\u0631 \u0634\u0645\u0627\u0633\u062a."
            }
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__ttqw)}>
          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__hurGf)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__f9Gsd
              )}
            >
              {"\u06a9\u0644\u06cc\u062f\u0648\u0627\u0698\u0647"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__tg8L3
              )}
            >
              {"\u0627\u0648\u0644\u0648\u06cc\u062a"}
            </div>
          </Stack__>
        </div>
        {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
          (() => {
            try {
              return $state.apiRequest.data.list;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return [];
              }
              throw e;
            }
          })()
        ).map((__plasmic_item_0, __plasmic_idx_0) => {
          const keywordcurrentItem = __plasmic_item_0;
          const keywordcurrentIndex = __plasmic_idx_0;
          return (
            <div
              className={classNames(projectcss.all, sty.freeBox__ahQ3)}
              key={keywordcurrentIndex}
              style={(() => {
                try {
                  return keywordcurrentIndex % 2 === 0
                    ? { "background-color": "#f0f0f0" }
                    : {};
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return { "background-color": "#f0f0f0" };
                  }
                  throw e;
                }
              })()}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__thoqj)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___1NjYy
                  )}
                >
                  <React.Fragment>
                    {(() => {
                      try {
                        return keywordcurrentItem.keyword;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return "";
                        }
                        throw e;
                      }
                    })()}
                  </React.Fragment>
                </div>
                <label
                  data-plasmic-name={"priorityField"}
                  data-plasmic-override={overrides.priorityField}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.priorityField
                  )}
                >
                  <div
                    className={projectcss.__wab_expr_html_text}
                    dangerouslySetInnerHTML={{
                      __html: (() => {
                        try {
                          return (() => {
                            function hslToRgb(h, s, l) {
                              let r, g, b;
                              if (s === 0) {
                                r = g = b = l;
                              } else {
                                const hue2rgb = (p, q, t) => {
                                  if (t < 0) t += 1;
                                  if (t > 1) t -= 1;
                                  if (t < 1 / 6) return p + (q - p) * 6 * t;
                                  if (t < 1 / 2) return q;
                                  if (t < 2 / 3)
                                    return p + (q - p) * (2 / 3 - t) * 6;
                                  return p;
                                };
                                const q = l < 0.5 ? l * (1 + s) : l + s - l * s;
                                const p = 2 * l - q;
                                r = hue2rgb(p, q, h + 1 / 3);
                                g = hue2rgb(p, q, h);
                                b = hue2rgb(p, q, h - 1 / 3);
                              }
                              return [r, g, b];
                            }
                            function pickContrastText([r, g, b]) {
                              const R = r * 255,
                                G = g * 255,
                                B = b * 255;
                              const yiq = (R * 299 + G * 587 + B * 114) / 1000;
                              return yiq >= 128 ? "black" : "white";
                            }
                            const p = keywordcurrentItem.priority;
                            const maxPriorityItem =
                              $state.apiRequest.data.list.reduce(
                                (acc, curr) =>
                                  curr.priority > acc.priority ? curr : acc,
                                { priority: 1 }
                              );
                            const maxPriority = maxPriorityItem.priority;
                            const minPriority = Math.min(
                              ...$state.apiRequest.data.list.map(
                                item => item.priority
                              )
                            );
                            const hue =
                              ((maxPriority - p) /
                                (maxPriority - minPriority)) *
                              120;
                            const bgH = hue / 360;
                            const bgS = 1;
                            const bgL = p < 3 ? 0.5 : p > 4 ? 0.6 : 0.55;
                            const rgb = hslToRgb(bgH, bgS, bgL);
                            const textColor = pickContrastText(rgb);
                            const output = `<span style="
    display: block;
    width: 100%;
    padding: 0.2em;
    color: ${textColor};
    background-color: hsl(${hue},100%,${bgL * 100}%);
    border-radius: 7px;
">${p}</span>`;
                            return output;
                          })();
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return "";
                          }
                          throw e;
                        }
                      })()
                    }}
                  />
                </label>
                <Button
                  children2={"\u0648\u06cc\u0631\u0627\u06cc\u0634"}
                  className={classNames("__wab_instance", sty.button__uJHyg)}
                  color={"clear"}
                  endIcon={
                    <Icon14Icon
                      className={classNames(projectcss.all, sty.svg__xsujO)}
                      role={"img"}
                    />
                  }
                  outline={true}
                  shape={"rounded"}
                  showEndIcon={true}
                  size={"minimal"}
                  startIcon={
                    <Icon14Icon
                      className={classNames(projectcss.all, sty.svg__qgdLy)}
                      role={"img"}
                    />
                  }
                />

                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__xm3Mf)}
                >
                  {(() => {
                    try {
                      return keywordcurrentItem.priority != 1;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return true;
                      }
                      throw e;
                    }
                  })() ? (
                    <Button
                      children2={
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___9Y6H5
                          )}
                        >
                          {
                            "\u0627\u0641\u0632\u0627\u06cc\u0634 \u0627\u0648\u0644\u0648\u06cc\u062a"
                          }
                        </div>
                      }
                      className={classNames(
                        "__wab_instance",
                        sty.button___3Icvg
                      )}
                      color={"clear"}
                      endIcon={
                        <Icon19Icon
                          className={classNames(projectcss.all, sty.svg__zmHoy)}
                          role={"img"}
                        />
                      }
                      onClick={async event => {
                        const $steps = {};

                        $steps["moveApiRequest"] = true
                          ? (() => {
                              const actionArgs = {
                                args: [
                                  "POST",
                                  (() => {
                                    try {
                                      return (
                                        "https://apigw.paziresh24.com/v1/n8n-search/webhook/d4d563fa-d0ad-4b86-bfd4-3e801fa8af00/vajegan/keywords/" +
                                        keywordcurrentItem.id +
                                        "/move"
                                      );
                                    } catch (e) {
                                      if (
                                        e instanceof TypeError ||
                                        e?.plasmicType ===
                                          "PlasmicUndefinedDataError"
                                      ) {
                                        return undefined;
                                      }
                                      throw e;
                                    }
                                  })(),
                                  undefined,
                                  { direction: "up", by: 1 }
                                ]
                              };
                              return $globalActions[
                                "Fragment.apiRequest"
                              ]?.apply(null, [...actionArgs.args]);
                            })()
                          : undefined;
                        if (
                          $steps["moveApiRequest"] != null &&
                          typeof $steps["moveApiRequest"] === "object" &&
                          typeof $steps["moveApiRequest"].then === "function"
                        ) {
                          $steps["moveApiRequest"] = await $steps[
                            "moveApiRequest"
                          ];
                        }

                        $steps["showToast"] = true
                          ? (() => {
                              const actionArgs = {
                                args: [
                                  (() => {
                                    try {
                                      return $steps.moveApiRequest.status ===
                                        200
                                        ? "success"
                                        : "error";
                                    } catch (e) {
                                      if (
                                        e instanceof TypeError ||
                                        e?.plasmicType ===
                                          "PlasmicUndefinedDataError"
                                      ) {
                                        return undefined;
                                      }
                                      throw e;
                                    }
                                  })(),
                                  (() => {
                                    try {
                                      return $steps.moveApiRequest.status ===
                                        200
                                        ? "تغییر اولویت کلیدواژه انجام شد"
                                        : "تغییر اولویت کلیدواژه با خطا مواجه شد";
                                    } catch (e) {
                                      if (
                                        e instanceof TypeError ||
                                        e?.plasmicType ===
                                          "PlasmicUndefinedDataError"
                                      ) {
                                        return undefined;
                                      }
                                      throw e;
                                    }
                                  })()
                                ]
                              };
                              return $globalActions[
                                "Fragment.showToast"
                              ]?.apply(null, [...actionArgs.args]);
                            })()
                          : undefined;
                        if (
                          $steps["showToast"] != null &&
                          typeof $steps["showToast"] === "object" &&
                          typeof $steps["showToast"].then === "function"
                        ) {
                          $steps["showToast"] = await $steps["showToast"];
                        }

                        $steps["runActionOnApiRequest"] = true
                          ? (() => {
                              const actionArgs = {
                                tplRef: "apiRequest",
                                action: "refresh"
                              };
                              return (({ tplRef, action, args }) => {
                                return $refs?.[tplRef]?.[action]?.(
                                  ...(args ?? [])
                                );
                              })?.apply(null, [actionArgs]);
                            })()
                          : undefined;
                        if (
                          $steps["runActionOnApiRequest"] != null &&
                          typeof $steps["runActionOnApiRequest"] === "object" &&
                          typeof $steps["runActionOnApiRequest"].then ===
                            "function"
                        ) {
                          $steps["runActionOnApiRequest"] = await $steps[
                            "runActionOnApiRequest"
                          ];
                        }
                      }}
                      outline={true}
                      shape={"rounded"}
                      showEndIcon={true}
                      size={"minimal"}
                      startIcon={
                        <Icon14Icon
                          className={classNames(projectcss.all, sty.svg__u4Fwi)}
                          role={"img"}
                        />
                      }
                    />
                  ) : null}
                  <Button
                    children2={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ev8X
                        )}
                      >
                        {
                          "\u06a9\u0627\u0647\u0634 \u0627\u0648\u0644\u0648\u06cc\u062a"
                        }
                      </div>
                    }
                    className={classNames("__wab_instance", sty.button__mJ68V)}
                    color={"clear"}
                    endIcon={
                      <Icon18Icon
                        className={classNames(projectcss.all, sty.svg__nG2Zr)}
                        role={"img"}
                      />
                    }
                    onClick={async event => {
                      const $steps = {};

                      $steps["moveApiRequest"] = true
                        ? (() => {
                            const actionArgs = {
                              args: [
                                "POST",
                                (() => {
                                  try {
                                    return (
                                      "https://apigw.paziresh24.com/v1/n8n-search/webhook/d4d563fa-d0ad-4b86-bfd4-3e801fa8af00/vajegan/keywords/" +
                                      keywordcurrentItem.id +
                                      "/move"
                                    );
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return undefined;
                                    }
                                    throw e;
                                  }
                                })(),
                                undefined,
                                { direction: "down", by: 1 }
                              ]
                            };
                            return $globalActions["Fragment.apiRequest"]?.apply(
                              null,
                              [...actionArgs.args]
                            );
                          })()
                        : undefined;
                      if (
                        $steps["moveApiRequest"] != null &&
                        typeof $steps["moveApiRequest"] === "object" &&
                        typeof $steps["moveApiRequest"].then === "function"
                      ) {
                        $steps["moveApiRequest"] = await $steps[
                          "moveApiRequest"
                        ];
                      }

                      $steps["invokeGlobalAction"] = true
                        ? (() => {
                            const actionArgs = {
                              args: [
                                (() => {
                                  try {
                                    return $steps.moveApiRequest.status === 200
                                      ? "success"
                                      : "error";
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return undefined;
                                    }
                                    throw e;
                                  }
                                })(),
                                (() => {
                                  try {
                                    return $steps.moveApiRequest.status === 200
                                      ? "تغییر اولویت کلیدواژه انجام شد"
                                      : "تغییر اولویت کلیدواژه با خطا مواجه شد";
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return undefined;
                                    }
                                    throw e;
                                  }
                                })()
                              ]
                            };
                            return $globalActions["Fragment.showToast"]?.apply(
                              null,
                              [...actionArgs.args]
                            );
                          })()
                        : undefined;
                      if (
                        $steps["invokeGlobalAction"] != null &&
                        typeof $steps["invokeGlobalAction"] === "object" &&
                        typeof $steps["invokeGlobalAction"].then === "function"
                      ) {
                        $steps["invokeGlobalAction"] = await $steps[
                          "invokeGlobalAction"
                        ];
                      }

                      $steps["runActionOnApiRequest"] = true
                        ? (() => {
                            const actionArgs = {
                              tplRef: "apiRequest",
                              action: "refresh"
                            };
                            return (({ tplRef, action, args }) => {
                              return $refs?.[tplRef]?.[action]?.(
                                ...(args ?? [])
                              );
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["runActionOnApiRequest"] != null &&
                        typeof $steps["runActionOnApiRequest"] === "object" &&
                        typeof $steps["runActionOnApiRequest"].then ===
                          "function"
                      ) {
                        $steps["runActionOnApiRequest"] = await $steps[
                          "runActionOnApiRequest"
                        ];
                      }
                    }}
                    outline={true}
                    shape={"rounded"}
                    showEndIcon={true}
                    size={"minimal"}
                    startIcon={
                      <Icon14Icon
                        className={classNames(projectcss.all, sty.svg__kK2Hd)}
                        role={"img"}
                      />
                    }
                  />
                </Stack__>
                <Button
                  children2={"\u062d\u0630\u0641"}
                  className={classNames("__wab_instance", sty.button__shj7D)}
                  color={"softRed"}
                  endIcon={
                    <Icon15Icon
                      className={classNames(projectcss.all, sty.svg___8MZs0)}
                      role={"img"}
                    />
                  }
                  onClick={async event => {
                    const $steps = {};

                    $steps["deleteKeywordRequest"] = true
                      ? (() => {
                          const actionArgs = {
                            args: [
                              "PATCH",
                              "https://apigw.paziresh24.com/v1/n8n-search/webhook/vajegan/keywords",
                              undefined,
                              (() => {
                                try {
                                  return [{ id: keywordcurrentItem.id }];
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return undefined;
                                  }
                                  throw e;
                                }
                              })()
                            ]
                          };
                          return $globalActions["Fragment.apiRequest"]?.apply(
                            null,
                            [...actionArgs.args]
                          );
                        })()
                      : undefined;
                    if (
                      $steps["deleteKeywordRequest"] != null &&
                      typeof $steps["deleteKeywordRequest"] === "object" &&
                      typeof $steps["deleteKeywordRequest"].then === "function"
                    ) {
                      $steps["deleteKeywordRequest"] = await $steps[
                        "deleteKeywordRequest"
                      ];
                    }

                    $steps["showTast"] = true
                      ? (() => {
                          const actionArgs = {
                            args: [
                              undefined,
                              "\u062f\u0631\u062e\u0648\u0627\u0633\u062a \u062d\u0630\u0641 \u06a9\u0644\u06cc\u062f\u0648\u0627\u0698\u0647 \u0627\u0631\u0633\u0627\u0644 \u0634\u062f."
                            ]
                          };
                          return $globalActions["Fragment.showToast"]?.apply(
                            null,
                            [...actionArgs.args]
                          );
                        })()
                      : undefined;
                    if (
                      $steps["showTast"] != null &&
                      typeof $steps["showTast"] === "object" &&
                      typeof $steps["showTast"].then === "function"
                    ) {
                      $steps["showTast"] = await $steps["showTast"];
                    }

                    $steps["refreshDataApiRequest"] = true
                      ? (() => {
                          const actionArgs = {
                            tplRef: "apiRequest",
                            action: "refresh"
                          };
                          return (({ tplRef, action, args }) => {
                            return $refs?.[tplRef]?.[action]?.(...(args ?? []));
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["refreshDataApiRequest"] != null &&
                      typeof $steps["refreshDataApiRequest"] === "object" &&
                      typeof $steps["refreshDataApiRequest"].then === "function"
                    ) {
                      $steps["refreshDataApiRequest"] = await $steps[
                        "refreshDataApiRequest"
                      ];
                    }
                  }}
                  outline={true}
                  size={"minimal"}
                  startIcon={
                    <Icon14Icon
                      className={classNames(projectcss.all, sty.svg__thI8)}
                      role={"img"}
                    />
                  }
                />
              </Stack__>
            </div>
          );
        })}
        <Stack__
          as={"div"}
          data-plasmic-name={"insertBox"}
          data-plasmic-override={overrides.insertBox}
          hasGap={true}
          className={classNames(projectcss.all, sty.insertBox)}
        >
          <Input
            data-plasmic-name={"input"}
            data-plasmic-override={overrides.input}
            className={classNames("__wab_instance", sty.input)}
            onChange={async (...eventArgs: any) => {
              generateStateOnChangeProp($state, ["input", "value"]).apply(
                null,
                eventArgs
              );
            }}
            placeholder={
              "\u06a9\u0644\u06cc\u062f\u0648\u0627\u0698\u0647 \u0645\u0648\u0631\u062f \u0646\u0638\u0631 \u0634\u0645\u0627"
            }
            type={"text"}
            value={generateStateValueProp($state, ["input", "value"])}
          />

          {false ? (
            <Select
              data-plasmic-name={"select"}
              data-plasmic-override={overrides.select}
              onChange={async (...eventArgs: any) => {
                generateStateOnChangeProp($state, ["select", "value"]).apply(
                  null,
                  eventArgs
                );
              }}
              onOpenChange={async (...eventArgs: any) => {
                generateStateOnChangeProp($state, ["select", "open"]).apply(
                  null,
                  eventArgs
                );
              }}
              open={generateStateValueProp($state, ["select", "open"])}
              options={(() => {
                const __composite = [
                  { label: null, value: null },
                  { label: null, value: null },
                  { label: null, value: null },
                  { label: null, value: null },
                  { label: null, value: null }
                ];
                __composite["0"]["label"] =
                  "\u0627\u0648\u0644\u0648\u06cc\u062a 1";
                __composite["0"]["value"] = "1";
                __composite["1"]["label"] =
                  "\u0627\u0648\u0644\u0648\u06cc\u062a 2";
                __composite["1"]["value"] = "2";
                __composite["2"]["label"] =
                  "\u0627\u0648\u0644\u0648\u06cc\u062a 3";
                __composite["2"]["value"] = "3";
                __composite["3"]["label"] =
                  "\u0627\u0648\u0644\u0648\u06cc\u062a 4";
                __composite["3"]["value"] = "4";
                __composite["4"]["label"] =
                  "\u0627\u0648\u0644\u0648\u06cc\u062a 5";
                __composite["4"]["value"] = "5";
                return __composite;
              })()}
              placeholder={
                "\u0627\u0648\u0644\u0648\u06cc\u062a \u0648\u0627\u0698\u0647 \u0631\u0627 \u0627\u0646\u062a\u062e\u0627\u0628 \u06a9\u0646\u06cc\u062f"
              }
              triggerClassName={classNames("__wab_instance", sty.select)}
              value={generateStateValueProp($state, ["select", "value"])}
            />
          ) : null}
          <Button
            children2={"\u0627\u0641\u0632\u0648\u062f\u0646"}
            className={classNames("__wab_instance", sty.button___6WM2)}
            onClick={async event => {
              const $steps = {};

              $steps["addApiRequest"] = true
                ? (() => {
                    const actionArgs = {
                      args: [
                        "POST",
                        "https://apigw.paziresh24.com/v1/n8n-search/webhook/vajegan/keywords",
                        undefined,
                        (() => {
                          try {
                            return [
                              {
                                keyword: $state.input.value,
                                priority: $state.select.value
                              }
                            ];
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return undefined;
                            }
                            throw e;
                          }
                        })()
                      ]
                    };
                    return $globalActions["Fragment.apiRequest"]?.apply(null, [
                      ...actionArgs.args
                    ]);
                  })()
                : undefined;
              if (
                $steps["addApiRequest"] != null &&
                typeof $steps["addApiRequest"] === "object" &&
                typeof $steps["addApiRequest"].then === "function"
              ) {
                $steps["addApiRequest"] = await $steps["addApiRequest"];
              }

              $steps["invokeGlobalAction2"] = true
                ? (() => {
                    const actionArgs = {
                      args: [
                        undefined,
                        (() => {
                          try {
                            return $steps.addApiRequest.status === 200
                              ? "افزودن کلیدواژه انجام شد"
                              : "افزودن کلیدواژه با خطا مواجه شد";
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return undefined;
                            }
                            throw e;
                          }
                        })()
                      ]
                    };
                    return $globalActions["Fragment.showToast"]?.apply(null, [
                      ...actionArgs.args
                    ]);
                  })()
                : undefined;
              if (
                $steps["invokeGlobalAction2"] != null &&
                typeof $steps["invokeGlobalAction2"] === "object" &&
                typeof $steps["invokeGlobalAction2"].then === "function"
              ) {
                $steps["invokeGlobalAction2"] = await $steps[
                  "invokeGlobalAction2"
                ];
              }

              $steps["runActionOnApiRequest"] = true
                ? (() => {
                    const actionArgs = {
                      tplRef: "apiRequest",
                      action: "refresh"
                    };
                    return (({ tplRef, action, args }) => {
                      return $refs?.[tplRef]?.[action]?.(...(args ?? []));
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["runActionOnApiRequest"] != null &&
                typeof $steps["runActionOnApiRequest"] === "object" &&
                typeof $steps["runActionOnApiRequest"].then === "function"
              ) {
                $steps["runActionOnApiRequest"] = await $steps[
                  "runActionOnApiRequest"
                ];
              }

              $steps["updateInputValue"] = true
                ? (() => {
                    const actionArgs = {
                      variable: {
                        objRoot: $state,
                        variablePath: ["input", "value"]
                      },
                      operation: 1
                    };
                    return (({ variable, value, startIndex, deleteCount }) => {
                      if (!variable) {
                        return;
                      }
                      const { objRoot, variablePath } = variable;

                      $stateSet(objRoot, variablePath, undefined);
                      return undefined;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateInputValue"] != null &&
                typeof $steps["updateInputValue"] === "object" &&
                typeof $steps["updateInputValue"].then === "function"
              ) {
                $steps["updateInputValue"] = await $steps["updateInputValue"];
              }
            }}
          />

          <Button
            children2={"\u0627\u0641\u0632\u0648\u062f\u0646"}
            className={classNames("__wab_instance", sty.button__pNEp)}
            onClick={async event => {
              const $steps = {};

              $steps["invokeGlobalAction"] = true
                ? (() => {
                    const actionArgs = {
                      args: [
                        "PATCH",
                        "https://apigw.paziresh24.com/v1/n8n-search/webhook/vajegan/keywords",
                        undefined,
                        (() => {
                          try {
                            return [
                              {
                                keyword: $state.input.value,
                                priority: $state.select.value
                              }
                            ];
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return undefined;
                            }
                            throw e;
                          }
                        })()
                      ]
                    };
                    return $globalActions["Fragment.apiRequest"]?.apply(null, [
                      ...actionArgs.args
                    ]);
                  })()
                : undefined;
              if (
                $steps["invokeGlobalAction"] != null &&
                typeof $steps["invokeGlobalAction"] === "object" &&
                typeof $steps["invokeGlobalAction"].then === "function"
              ) {
                $steps["invokeGlobalAction"] = await $steps[
                  "invokeGlobalAction"
                ];
              }

              $steps["invokeGlobalAction2"] = true
                ? (() => {
                    const actionArgs = {
                      args: [
                        undefined,
                        (() => {
                          try {
                            return "asdasd";
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return undefined;
                            }
                            throw e;
                          }
                        })()
                      ]
                    };
                    return $globalActions["Fragment.showToast"]?.apply(null, [
                      ...actionArgs.args
                    ]);
                  })()
                : undefined;
              if (
                $steps["invokeGlobalAction2"] != null &&
                typeof $steps["invokeGlobalAction2"] === "object" &&
                typeof $steps["invokeGlobalAction2"].then === "function"
              ) {
                $steps["invokeGlobalAction2"] = await $steps[
                  "invokeGlobalAction2"
                ];
              }

              $steps["runActionOnApiRequest"] = true
                ? (() => {
                    const actionArgs = {
                      tplRef: "apiRequest",
                      action: "refresh"
                    };
                    return (({ tplRef, action, args }) => {
                      return $refs?.[tplRef]?.[action]?.(...(args ?? []));
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["runActionOnApiRequest"] != null &&
                typeof $steps["runActionOnApiRequest"] === "object" &&
                typeof $steps["runActionOnApiRequest"].then === "function"
              ) {
                $steps["runActionOnApiRequest"] = await $steps[
                  "runActionOnApiRequest"
                ];
              }

              $steps["updateInputValue"] = true
                ? (() => {
                    const actionArgs = {
                      variable: {
                        objRoot: $state,
                        variablePath: ["input", "value"]
                      },
                      operation: 1
                    };
                    return (({ variable, value, startIndex, deleteCount }) => {
                      if (!variable) {
                        return;
                      }
                      const { objRoot, variablePath } = variable;

                      $stateSet(objRoot, variablePath, undefined);
                      return undefined;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateInputValue"] != null &&
                typeof $steps["updateInputValue"] === "object" &&
                typeof $steps["updateInputValue"].then === "function"
              ) {
                $steps["updateInputValue"] = await $steps["updateInputValue"];
              }
            }}
            outline={true}
          />
        </Stack__>
      </ApiRequest>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "apiRequest",
    "h6",
    "priorityField",
    "insertBox",
    "input",
    "select"
  ],
  apiRequest: [
    "apiRequest",
    "h6",
    "priorityField",
    "insertBox",
    "input",
    "select"
  ],
  h6: ["h6"],
  priorityField: ["priorityField"],
  insertBox: ["insertBox", "input", "select"],
  input: ["input"],
  select: ["select"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  apiRequest: typeof ApiRequest;
  h6: "h6";
  priorityField: "label";
  insertBox: "div";
  input: typeof Input;
  select: typeof Select;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicVajegan__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicVajegan__VariantsArgs;
    args?: PlasmicVajegan__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicVajegan__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicVajegan__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicVajegan__ArgProps,
          internalVariantPropNames: PlasmicVajegan__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicVajegan__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicVajegan";
  } else {
    func.displayName = `PlasmicVajegan.${nodeName}`;
  }
  return func;
}

export const PlasmicVajegan = Object.assign(
  // Top-level PlasmicVajegan renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    apiRequest: makeNodeComponent("apiRequest"),
    h6: makeNodeComponent("h6"),
    priorityField: makeNodeComponent("priorityField"),
    insertBox: makeNodeComponent("insertBox"),
    input: makeNodeComponent("input"),
    select: makeNodeComponent("select"),

    // Metadata about props expected for PlasmicVajegan
    internalVariantProps: PlasmicVajegan__VariantProps,
    internalArgProps: PlasmicVajegan__ArgProps
  }
);

export default PlasmicVajegan;
/* prettier-ignore-end */
