/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: aU6fPsMDSmKqgHWpAbdgs
// Component: inlyH9E0KabP

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Vajegan from "../../Vajegan"; // plasmic-import: RM0X42We8_T_/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_fragment_design_system_css from "../fragment_design_system/plasmic.module.css"; // plasmic-import: h9Dbk9ygddw7UVEq1NNhKi/projectcss
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: aU6fPsMDSmKqgHWpAbdgs/projectcss
import sty from "./PlasmicVajeganPage.module.css"; // plasmic-import: inlyH9E0KabP/css

createPlasmicElementProxy;

export type PlasmicVajeganPage__VariantMembers = {};
export type PlasmicVajeganPage__VariantsArgs = {};
type VariantPropType = keyof PlasmicVajeganPage__VariantsArgs;
export const PlasmicVajeganPage__VariantProps = new Array<VariantPropType>();

export type PlasmicVajeganPage__ArgsType = {};
type ArgPropType = keyof PlasmicVajeganPage__ArgsType;
export const PlasmicVajeganPage__ArgProps = new Array<ArgPropType>();

export type PlasmicVajeganPage__OverridesType = {
  کلیدواژهها?: Flex__<"div">;
  vajegan?: Flex__<typeof Vajegan>;
};

export interface DefaultVajeganPageProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicVajeganPage__RenderFunc(props: {
  variants: PlasmicVajeganPage__VariantsArgs;
  args: PlasmicVajeganPage__ArgsType;
  overrides: PlasmicVajeganPage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={
            "\u06a9\u0644\u06cc\u062f\u0648\u0627\u0698\u0647\u0647\u0627"
          }
          data-plasmic-override={overrides.کلیدواژهها}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_fragment_design_system_css.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.کلیدواژهها
          )}
        >
          <Vajegan
            data-plasmic-name={"vajegan"}
            data-plasmic-override={overrides.vajegan}
            className={classNames("__wab_instance", sty.vajegan)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  کلیدواژهها: [
    "\u06a9\u0644\u06cc\u062f\u0648\u0627\u0698\u0647\u0647\u0627",
    "vajegan"
  ],
  vajegan: ["vajegan"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  کلیدواژهها: "div";
  vajegan: typeof Vajegan;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicVajeganPage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicVajeganPage__VariantsArgs;
    args?: PlasmicVajeganPage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicVajeganPage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicVajeganPage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicVajeganPage__ArgProps,
          internalVariantPropNames: PlasmicVajeganPage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicVajeganPage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (
    nodeName === "\u06a9\u0644\u06cc\u062f\u0648\u0627\u0698\u0647\u0647\u0627"
  ) {
    func.displayName = "PlasmicVajeganPage";
  } else {
    func.displayName = `PlasmicVajeganPage.${nodeName}`;
  }
  return func;
}

export const PlasmicVajeganPage = Object.assign(
  // Top-level PlasmicVajeganPage renders the root element
  makeNodeComponent(
    "\u06a9\u0644\u06cc\u062f\u0648\u0627\u0698\u0647\u0647\u0627"
  ),
  {
    // Helper components rendering sub-elements
    vajegan: makeNodeComponent("vajegan"),

    // Metadata about props expected for PlasmicVajeganPage
    internalVariantProps: PlasmicVajeganPage__VariantProps,
    internalArgProps: PlasmicVajeganPage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicVajeganPage;
/* prettier-ignore-end */
