/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: aU6fPsMDSmKqgHWpAbdgs

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsoNzAawMQhZv4 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: oNZAawMQhZV4/globalVariant
import { useScreenVariants as useScreenVariantsqmLtHiTXdNxv } from "../fragment_design_system/PlasmicGlobalVariant__Screen"; // plasmic-import: QmLtHiTXdNxv/globalVariant
import { useScreenVariants as useScreenVariantsbr2UhI7UlpvR } from "../fragment_icons/PlasmicGlobalVariant__Screen"; // plasmic-import: BR2UhI7ulpvR/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsoNzAawMQhZv4,
  screen: useScreenVariantsqmLtHiTXdNxv,
  screen: useScreenVariantsbr2UhI7UlpvR
});
