// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: aU6fPsMDSmKqgHWpAbdgs
// Component: oqH1E7yoY1w4

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import DynamicPagePageSection from "../../DynamicPagePageSection"; // plasmic-import: w-k8SPtgF7fV/component
import ScriptsAndGeneralTags from "../../ScriptsAndGeneralTags"; // plasmic-import: zZNx54MRT-Br/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_fragment_design_system_css from "../fragment_design_system/plasmic.module.css"; // plasmic-import: h9Dbk9ygddw7UVEq1NNhKi/projectcss
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: aU6fPsMDSmKqgHWpAbdgs/projectcss
import sty from "./PlasmicBookingOptions.module.css"; // plasmic-import: oqH1E7yoY1w4/css

createPlasmicElementProxy;

export type PlasmicBookingOptions__VariantMembers = {};
export type PlasmicBookingOptions__VariantsArgs = {};
type VariantPropType = keyof PlasmicBookingOptions__VariantsArgs;
export const PlasmicBookingOptions__VariantProps = new Array<VariantPropType>();

export type PlasmicBookingOptions__ArgsType = {};
type ArgPropType = keyof PlasmicBookingOptions__ArgsType;
export const PlasmicBookingOptions__ArgProps = new Array<ArgPropType>();

export type PlasmicBookingOptions__OverridesType = {
  root?: Flex__<"div">;
  dynamicPagePageSection?: Flex__<typeof DynamicPagePageSection>;
  scriptsAndGeneralTags?: Flex__<typeof ScriptsAndGeneralTags>;
};

export interface DefaultBookingOptionsProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicBookingOptions__RenderFunc(props: {
  variants: PlasmicBookingOptions__VariantsArgs;
  args: PlasmicBookingOptions__ArgsType;
  overrides: PlasmicBookingOptions__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_fragment_design_system_css.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root
          )}
        >
          <DynamicPagePageSection
            data-plasmic-name={"dynamicPagePageSection"}
            data-plasmic-override={overrides.dynamicPagePageSection}
            className={classNames("__wab_instance", sty.dynamicPagePageSection)}
            dataSourceUrl={`https://apigw.paziresh24.com/v1/ui-jahannama/booking_selection_page_ui/${$ctx.query.document_id}`}
          />

          <ScriptsAndGeneralTags
            data-plasmic-name={"scriptsAndGeneralTags"}
            data-plasmic-override={overrides.scriptsAndGeneralTags}
            className={classNames("__wab_instance", sty.scriptsAndGeneralTags)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "dynamicPagePageSection", "scriptsAndGeneralTags"],
  dynamicPagePageSection: ["dynamicPagePageSection"],
  scriptsAndGeneralTags: ["scriptsAndGeneralTags"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  dynamicPagePageSection: typeof DynamicPagePageSection;
  scriptsAndGeneralTags: typeof ScriptsAndGeneralTags;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicBookingOptions__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicBookingOptions__VariantsArgs;
    args?: PlasmicBookingOptions__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicBookingOptions__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicBookingOptions__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicBookingOptions__ArgProps,
          internalVariantPropNames: PlasmicBookingOptions__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicBookingOptions__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBookingOptions";
  } else {
    func.displayName = `PlasmicBookingOptions.${nodeName}`;
  }
  return func;
}

export const PlasmicBookingOptions = Object.assign(
  // Top-level PlasmicBookingOptions renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    dynamicPagePageSection: makeNodeComponent("dynamicPagePageSection"),
    scriptsAndGeneralTags: makeNodeComponent("scriptsAndGeneralTags"),

    // Metadata about props expected for PlasmicBookingOptions
    internalVariantProps: PlasmicBookingOptions__VariantProps,
    internalArgProps: PlasmicBookingOptions__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicBookingOptions;
/* prettier-ignore-end */
